kind = "mobile"
previewPath = "/"
title = "Where's Fishy"
version = "1.0.0"
id = "artifacts/wheres-fishy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23518

[services.development]
run = "pnpm --filter @workspace/wheres-fishy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wheres-fishy", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wheres-fishy", "run", "serve" ]

[services.env]
PORT = "23518"
BASE_PATH = "/"
